#!/usr/bin/env bash
set -euo pipefail

# Check if the user has sudo privileges
#if ! [ $(sudo -n true; echo $?) -eq 0 ]; then
#    exit 1
#fi

sudo grub-reboot 'Windows 10 (on /dev/sda1)'
systemctl reboot
